version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=lahmadb
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:6.3.1-fpm-alpine
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=lahmadb
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes/maker:/var/www/html/wp-content/themes/maker 
      - ./wp-content/themes/lahma_maker:/var/www/html/wp-content/themes/lahma_maker
      - ./wp-content/plugins/stripe-for-lahmacun:/var/www/html/wp-content/plugins/stripe-for-lahmacun 
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.16.1-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes/maker:/var/www/html/wp-content/themes/maker 
      - ./wp-content/themes/lahma_maker:/var/www/html/wp-content/themes/lahma_maker 
      - ./wp-content/plugins/stripe-for-lahmacun:/var/www/html/wp-content/plugins/stripe-for-lahmacun
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge 
